### ISSUE TITLE
ENH: allow gene prediction from `SampleData[MAGs]`

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-moshpit#101]
**Is your feature request related to a problem? Please describe.**
Currently, predicting genes on dereplicated MAGs is only possible. It would be great if we could also do it on un-dereplicated MAGs.

**Describe the solution you'd like**
Add `SampleData[MAGs]` as accepted input to the `predict-genes-prodigal` action.

**Comment by Sann5** [comment]
@michal I think this would be fairly straightforward to implement. As of now the action simply iterates through the fasta files in the `FeatureData[MAG]` artifact and runs prodigal on each one. For `SampleData[MAGs]` we would only have to iterate also over samples. One detail that has to be sorted out is the output. If we would like the output of a `SampleData[MAGs]` input to also be sorted in folders by sample then we would need to implement new semantic types (unless they already exist and I overlooked them just now going through the `per_sample_data` semantic types). Another option is simply to prepend the sample name to the MAG ID and put everything in the same folder. What do you think is best?
