### ISSUE TITLE
MAINT: clean up the input parameters to `evaluate-busco`

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-moshpit#113]
Here's a list of corrections to be made to the current list of parameters:

- `only the 'genome' or 'geno' option is supported`: remove `geno`
- ` --p-download TEXT...` + the other `download`-related flags: we should remove those - if we want to download anything it should become a separate action, the output of which should then become input to this action here
- `--p-help`: remove - this doesn't do anything
- `--p-list-datasets`: remove - this doesn't do anything
- `--p-offline`: remove as without download it would not work right now
- `--p-restart`: this also probably does not work in our use case
- `--p-tar`: I guess this also is not required here as we write everything to a tmp dir which gets deleted afterwards
- `--p-update-data`: nothing to update there as we re-fetch fresh data every time
- `--p-version`: remove - this doesn't do anything

**Comment by Sann5** [comment]
@misialq 
> --p-download TEXT... + the other download-related flags: we should remove those - if we want to download anything it should become a separate action, the output of which should then become input to this action here

Indeed the way we are using BUSCO now it ALWAYS downloads data from the internet and uses it to identify BUSCO genes in the analyzed sequence. This data is then thrown away. I can work on an action to download the data and then use the output as input for `evaluate-busco`, but I would od it in a separate PR

**Comment by misialq** [comment]
Makes sense - can you just create a new issue for that and remove this flag altogether for now? Thanks!
