### ISSUE TITLE
BUG: wrong description for --i-busco-db in `evaluate-busco`

### ISSUE THREAD

**Issue by VinzentRisch** [bokulich-lab/q2-moshpit#214]
**Describe the bug**
The description for --i-busco-db in `evaluate-busco` says:
"BUSCO database. If provided BUSCO will run in
 offline mode. If not provided a BUSCO database will
 be downloaded to a temporary location and then
 deleted."
 
 But this is not true, if the db is not provided there is this error:
 `There was a problem with the command:`           
 `(1/1) Missing option '--i-busco-db'.`
 
 In the code it also does not look like this functionality was added, so I think the description is just wrong.

**To Reproduce**
`qiime moshpit evaluate-busco --i-bins mags.qza --output-dir out`

**Please complete the following information:**
 - OS:  macOS
 - QIIME 2 version: 2024.10.0.dev0+28.g10bb850

**Comment by misialq** [comment]
Hey @VinzentRisch, just to clarify: you mean that functionality of downloading the DB if not provided was not added?

**Comment by VinzentRisch** [comment]
Yes I mean that is not a problem, but then it should be removed from the description. 
Should I remove it?

**Comment by misialq** [comment]
Yeah, that would be nice - otherwise it's a bit confusing... Thanks!
