### ISSUE TITLE
add action for estimating (relative) abundances MAGs/MAG-based taxonomic profiles

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/q2-moshpit#33]
When performing taxonomic profiling of MAGs, abundance information currently is not preserved. This is needed to then estimate the (relative) abundances of MAGs/taxa.

This can be done in a few steps:
1. map reads to MAGs.
2. normalize by genome length, e.g., calculate RPKM or similar. c.f., [bracken uses genome length](https://peerj.com/articles/cs-104/) to calculate relative abundances of taxa when doing read-based profiling.

This action should probably be independent to taxonomic classification, i.e., to output a feature table of MAG abundances per sample. 

Some useful reading
1. [Challenges in benchmarking metagenomic profilers](https://www.nature.com/articles/s41592-021-01141-3) describes the differences between sequence abundance and taxon abundance for estimating relative abundances in metagenomes. 
2. [mOTUs2](https://www.nature.com/articles/s41467-019-08844-4) uses a single-copy marker-gene approach for accurately estimating taxonomic abundance from reads, but gives a good overview of the different approaches and a comparison vs. MAGs.

**Comment by misialq** [comment]
Closed by https://github.com/bokulich-lab/q2-moshpit/pull/177
