### ISSUE TITLE
add missing tests for the kraken2 classification

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-moshpit#51]
As discussed on #38, let's wrap up the Kraken 2 integration by:
- [x]  adding the missing tests of report parsing (@ebolyen)
- [x] dropping the unnecessary taxonomy annotation from the feature data artifact (https://github.com/bokulich-lab/q2-moshpit/pull/38#issuecomment-1626024502) (@ebolyen)
- [ ] regression test of report generation (@gregcaporaso)

**Comment by gregcaporaso** [comment]
I think we can close this, unless you have anything specific in mind that we should still cover. I don't remember exactly what we had planned re: report generation, but feel free to re-open.
