### ISSUE TITLE
add support for kraken2-inspect to generate reports about kraken databases

### ISSUE THREAD

**Issue by gregcaporaso** [bokulich-lab/q2-moshpit#65]
Documentation on this can be found [here](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#inspecting-a-kraken-2-databases-contents). Specifically I could see a searchable report being useful for assessing whether taxa of interest (including a host's taxon) are present in a database, and in finding information on things like the number of distinct minimizers in the database that are associated with a taxon (which could be useful as feature metadata). If the output were of type `ImmutableMetadata` keyed on taxon id, that could let us use the information as feature metadata, or generate a searchable .qzv with `metadata tabulate`.

**Comment by gregcaporaso** [comment]
@colinvwood is going to jump in on this now.

**Comment by colinvwood** [comment]
closed by bokulich-lab/q2-types-genomics#62 and #95
