### ISSUE TITLE
BUG: Environment Missing Altair

### ISSUE THREAD

**Issue by Oddant1** [bokulich-lab/q2-moshpit#82]
When I created a conda environment from the [2023.9/shotgun/released/ubuntu](https://github.com/qiime2/distributions/blob/dev/2023.9/shotgun/released/qiime2-shotgun-ubuntu-latest-conda.yml) environment file and ran `make test` on the moshpit main branch, I got an error about not having altair installed. I conda installed altair and it resolved the issue.

**Comment by misialq** [comment]
Hey @Oddant1, thanks for reporting that! I believe that the reason for this is the busco action actually not being included in the 2023.9 release: when I compare the commit history on the `main` branch vs. the `release-2023.9` I can see that the latter one has one bug fix cherry-picked from the main branch but skips the busco commit (plus some other ones). Which raises a question for me: is that a problem or is it fine? @ebolyen could you maybe advise a bit on that? I guess when the next release branch comes everything should be fixed again, right?

**Comment by ebolyen** [comment]
I think this is going to end up being fine, as the recipe has altair in it. So the next prepare (which I'm working on) will have that in the next dev env (and release).
